### ISSUE TITLE
Update documentation to reference command line arguments

### ISSUE THREAD

**Issue by jamesgiu** [jamesgiu/google-business-finder#4]
Recently, an issue (https://github.com/jamesgiu/google-business-finder/issues/2) changed a const to a CLA. 
Please update the documentation to reflect how to use the Python script now.

**Comment by ghost** [comment]
I'll have a shot at this.

**Comment by jamesgiu** [comment]
Hi @krustocious27, thank you! I appreciate your PR. Happy hacktoberfest
